apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas

bases:
  - ../../base

images:
  - name: atlas-platform
    newName: 733508956784.dkr.ecr.us-east-1.amazonaws.com/atlas-platform-prod

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: atlas-platform
      spec:
        replicas: 3
        template:
          spec:
            containers:
            - name: atlas-platform
              env:
              - name: SPRING_PROFILES_ACTIVE
                value: "prod"
